
sidebars:

    #
    # Product five sidebar
    #
    - label: "docgenSidebar"
      items:

         #
         # Product five documentation top page
         #
          - label: "DocGen documentation"
            title: "Welcome DocGen documentation"
            slug: "overview"
            brief: "Develop documentation with additional topics and categories in the `products.outline.yaml` in the `product-five-sidebar` sidebar definition"
